Use config-file instead of edit-config
Workaround for
Failed to install 'cordova-plugin-bambuser': TypeError: doc.find is not a function

...during reinstallation after uninstallation

https://stackoverflow.com/a/51644122